### ISSUE TITLE
topology is deprecated from keras.engine

### ISSUE THREAD

**Issue by jepierre** [matterport/Mask_RCNN#724]
load_weights function from MaskRCNN is not working on suggested version 2.0.8 of Keras. This is because the topology package is no longer supported in Keras. Please update the requirements.txt with correct version of Keras or remove imports of topology and replace with saving. Below is the error I get wusing the demo code.

AttributeError: module 'keras.engine.topology' has no attribute 'load_weights_from_hdf5_group_by_name'

**Comment by engineer1109** [comment]
Look for the previous issues to find the answers.
--PS 咸鱼太多

**Comment by waleedka** [comment]
Fixed in https://github.com/matterport/Mask_RCNN/pull/662
