### ISSUE TITLE
Tensorflow 2.0 parallel_model problem 

### ISSUE THREAD

**Issue by hxfdanger** [matterport/Mask_RCNN#2126]
I'm trying to use mrcnn today but i had this problem. 
do you have an idea for the solution ? 

```
model = modellib.MaskRCNN(mode="training", config=config, model_dir=args.logs)
  File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 1835, in __init__
  File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2060, in build
  File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/parallel_model.py", line 37, in __init__
  File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/parallel_model.py", line 79, in make_parallel
  File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/parallel_model.py", line 79, in <listcomp>
  File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/keras/engine/base_layer.py", line 443, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/keras/engine/base_layer.py", line 1311, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
AttributeError: 'Node' object has no attribute 'output_masks' 
```

**Comment by sheyifei2019** [comment]
this mask R-CNN can use tf2.0?

**Comment by hxfdanger** [comment]
@sheyifei2019, i think : https://github.com/matterport/Mask_RCNN/pull/1896

**Comment by Altimis** [comment]
I have the exact same problem ... 
I'm changing the code and everytime I get an error regarding the tf version. Is there a version of mask rcnn that supports tf 2.1 ?

**Comment by hxfdanger** [comment]
@Altimis, i don't think if there are a version supports tf 2.1.. 
For my problem, I managed to make it work on tf 2.0. with multi-GPU.

**Comment by andreap9** [comment]
> I'm trying to use mrcnn today but i had this problem.
> do you have an idea for the solution ?
> 
> ```
> model = modellib.MaskRCNN(mode="training", config=config, model_dir=args.logs)
>   File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 1835, in __init__
>   File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2060, in build
>   File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/parallel_model.py", line 37, in __init__
>   File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/parallel_model.py", line 79, in make_parallel
>   File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/parallel_model.py", line 79, in <listcomp>
>   File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/keras/engine/base_layer.py", line 443, in __call__
>     previous_mask = _collect_previous_mask(inputs)
>   File "/hdd-raid0/home_server/houssem/anaconda3/envs/hxf_env/lib/python3.7/site-packages/keras/engine/base_layer.py", line 1311, in _collect_previous_mask
>     mask = node.output_masks[tensor_index]
> AttributeError: 'Node' object has no attribute 'output_masks' 
> ```

I had the same error and I solved it by replacing in parallel_model.py all import keras with import tensorflow.keras. It seems that this error occurs when keras and tensorflow.keras mix up.

**Comment by burhr2** [comment]
Hi! kindly see this issue https://github.com/matterport/Mask_RCNN/issues/2312 there is a pointer to the same implementation that supports TensorFlow 2=>. If this solves your problem kindly close the issue so as others can navigate to other issues easier
