### PR TITLE
 support to save image with detection result

### PR DESCRIPTION
**Pull request by PaulChongPeng**
save_image(image, image_name, boxes, masks, class_ids, scores, class_names,                 filter_classs_names=None,
                       scores_thresh=0.1, save_dir=None, mode=0)
    
        image: image array
        image_name: image name
        boxes: [num_instance, (y1, x1, y2, x2, class_id)] in image coordinates.
        masks: [num_instances, height, width]
        class_ids: [num_instances]
        scores: confidence scores for each box
        class_names: list of class names of the dataset
        filter_classs_names: (optional) list of class names we want to draw
        scores_thresh: (optional) threshold of confidence scores
        save_dir: (optional) the path to store image
        mode: (optional) select the result which you want
                mode = 0 , save image with bbox,class_name,score and mask;
                mode = 1 , save image with bbox,class_name and score;
                mode = 2 , save image with class_name,score and mask;
                mode = 3 , save mask with black background;

demo code 

    image = skimage.io.imread(os.path.join(IMAGE_DIR,image_name))
    results = model.detect([image], verbose=1)
    r = results[0]
    visualize.save_image(image, image_name, r['rois'], r['masks'],
        r['class_ids'],r['scores'],coco_class_names,
        filter_classs_names=['bottle', 'wine glass'],scores_thresh=0.9,mode=0)

### CODE REVIEW

**Comment by waleedka** [comment]
There was a [previous discussion](https://github.com/matterport/Mask_RCNN/pull/3) about splitting some the visualization functions such that the code that generates the image is separate and can be called from a parent function that either displays or saves the images. I think that would reduce code duplication, compared to adding the new function that duplicates some of the code of the other functions. 

Unless this includes new functionality?

**Comment by PaulChongPeng** [comment]
I know that you are refactoring the function in visualize.py as we talked in [issues 33](https://github.com/matterport/Mask_RCNN/issues/33) .
I think you want to merge some function in one method, so I add the methon save_image() with function:
1.filter the detect results with filter_classs_names user want
2.filter the detect results with scores_thresh user want
3.user could select mask or bbox or both them to be saved with image
4.user could just save Semantic Segmentation image which is useful

**Comment by PaulChongPeng** [comment]
If you want to merge the pull request , I think I shold create a new pull request.
This  pull request has three commits but only one is useful.
If you don't want to merge it, I will not create a new one

**Review by beykaei — COMMENTED** [review]
Why these changes are not in the visualize.py to be downloaded?

**Comment by fastlater** [comment]
@PaulChongPeng  your  save_image function is not available in the visualize.py. It was renamed or just dont include? I maybe will copy and paste that piece of code.

**Comment by John1231983** [comment]
@PaulChongPeng: Could you tell me how we can save the prediction probability of masks, instead of the binary mask?

**Comment by PaulChongPeng** [comment]
My code has not merged to the master.
If you want to try it, you can get it in : https://github.com/matterport/Mask_RCNN/pull/38/commits/bc8f148b820ebd45246ed358a120c99b09798d71

**Comment by John1231983** [comment]
I know that branch. However, I want to save the mask probability instead of the binary mask. Could we do it? For example, I have one object in the image, I want to segment it and save the object with its probability map, instead of binary (1,0) as current output of this project.

**Comment by my3jie** [comment]
@PaulChongPeng 
Thanks for your codes!
well I  replaced your visualize.py file to the original file in my folder and just added a line in inspect_balloon_data.ipynb as follows:
############## NEW ADDED LINE ########################## 
from mrcnn.visualize import save_image

############## NEW ADDED LINE ########################## 

but it told me it cannot import name 'save_image', Did i do sth wrong?

thank you for your help!

**Comment by ZuxianShi** [comment]
thank you very much! I'm success.
add [to](https://github.com/matterport/Mask_RCNN/commit/bc8f148b820ebd45246ed358a120c99b09798d71) visualize

**Comment by jamesthesken** [comment]
This would be a very useful feature, especially for implementing a semi-supervised approach for training new data. ie. return new polygon coordinates from predicted mask to be used in VGG for selecting/deselecting bad predictions.

**Comment by umair-sabir** [comment]
How to save image with no detection. When i try to save the image using save_image function, then it can only save images with detected classes. But how to save images if something not detected. Thanks

**Comment by umair-sabir** [comment]
@PaulChongPeng  

Hi,

I cannot change the font color while i save images using your save_image function. Can you please tell me the way to change font color ?

Thanks

**Comment by lapetite123** [comment]
I have only changed visualize.py to save image, but when I run 'python samples/coco/coco.py evaluate --dataset=/home/COCO_datatset --model=last', there is no saving inference image, anywhere else should I change in the code ? waiting for your reply

**Comment by mooooon333** [comment]
> @PaulChongPeng
> Thanks for your codes!
> well I replaced your visualize.py file to the original file in my folder and just added a line in inspect_balloon_data.ipynb as follows:
> ############## NEW ADDED LINE ##########################
> from mrcnn.visualize import save_image
> 
> ############## NEW ADDED LINE ##########################
> 
> but it told me it cannot import name 'save_image', Did i do sth wrong?
> 
> thank you for your help!

`>>> print(visualize)
<module 'mrcnn.visualize' from 'E:\\anaconda\\lib\\site-packages\\mask_rcnn-2.1-py3.6.egg\\mrcnn\\visualize.py'>`
是import模块的顺序问题，系统查找时先找到了其他地方的visualize.py而不是你修改的那个

**Comment by amrbenattia** [comment]
I am applying visualize.save_image but the result always as below
*** No instances in image -image name-to draw *** 

anyone could help

**Comment by kakashi571** [comment]
I just want to save the green coloured boxes as separate images. just the detected parts.

**Comment by sheep1234567** [comment]
@PaulChongPeng 
Hi, thanks for the image saving code. 
but when I tried to save, it occurs such error, do you know why?

image

image

**Comment by lapetite123** [comment]
@sheep1234567 I got the same error too, and I changed another way to solve it.
In inference.py:
count = os.listdir(IMAGE_DIR)
for i in range(0,len(count)):
    path = os.path.join(IMAGE_DIR, count[i])
    if os.path.isfile(path):
        file_names = next(os.walk(IMAGE_DIR))[2]
        image = skimage.io.imread(os.path.join(IMAGE_DIR, count[i]))
        # Run detection
        results = model.detect([image], verbose=1)
        r = results[0]
        visualize.display_instances(count[i],image, r['rois'], r['masks'], r['class_ids'],
                            class_names, r['scores'])

and in visualize.py you might need to add ' mpl.use('Agg') '

**Comment by sheep1234567** [comment]
> @sheep1234567 I got the same error too, and I changed another way to solve it.
> In inference.py:
> count = os.listdir(IMAGE_DIR)
> for i in range(0,len(count)):
> path = os.path.join(IMAGE_DIR, count[i])
> if os.path.isfile(path):
> file_names = next(os.walk(IMAGE_DIR))[2]
> image = skimage.io.imread(os.path.join(IMAGE_DIR, count[i]))
> # Run detection
> results = model.detect([image], verbose=1)
> r = results[0]
> visualize.display_instances(count[i],image, r['rois'], r['masks'], r['class_ids'],
> class_names, r['scores'])
> 
> and in visualize.py you might need to add ' mpl.use('Agg') '

Thanks lapetite123,
But I was hoping to save image instead of display, besides, I find there is no difference between the code you offered and the one Matterport wrote in demo.ipynb. Is there any other way I can save image? Thanks help!

And after I add mpl.use('Agg'), 
image
still occurs.

**Comment by lapetite123** [comment]
I forgot to tell the change in display_instances! I will tell you tomorrow morning

**Comment by lapetite123** [comment]
@sheep1234567 this is is my display_instances in visualize.py
def display_instances(count,image, boxes, masks, class_ids, class_names,
                      scores=None, title="",
                      figsize=(16, 16), ax=None):
    """
    boxes: [num_instance, (y1, x1, y2, x2, class_id)] in image coordinates.
    masks: [num_instances, height, width]
    class_ids: [num_instances]
    class_names: list of class names of the dataset
    scores: (optional) confidence scores for each box
    figsize: (optional) the size of the image.
    """
    # Number of instances
    N = boxes.shape[0]
    if not N:
        print("\n*** No instances to display *** \n")
    else:
        assert boxes.shape[0] == masks.shape[-1] == class_ids.shape[0]
    if not ax:
        _, ax = plt.subplots(1, figsize=figsize)
    # Generate random colors
    colors = random_colors(N)
    # Show area outside image boundaries.
    height, width = image.shape[:2]
    ax.set_ylim(height + 10, -10)
    ax.set_xlim(-10, width + 10)
    ax.axis('off')
    ax.set_title(title)
    masked_image = image.astype(np.uint32).copy()
    for i in range(N):
        color = colors[i]
        # Bounding box
        if not np.any(boxes[i]):
            # Skip this instance. Has no bbox. Likely lost in image cropping.
            continue
        y1, x1, y2, x2 = boxes[i]
        p = patches.Rectangle((x1, y1), x2 - x1, y2 - y1, linewidth=2,
                              alpha=0.7, linestyle="dashed",
                              edgecolor=color, facecolor='none')
        ax.add_patch(p)
        # Label
        class_id = class_ids[i]
        score = scores[i] if scores is not None else None
        label = class_names[class_id]
        x = random.randint(x1, (x1 + x2) // 2)
        caption = "{} {:.3f}".format(label, score) if score else label
        ax.text(x1, y1 + 8, caption,
                color='w', size=11, backgroundcolor="none")
        # Mask
        mask = masks[:, :, i]
        masked_image = apply_mask(masked_image, mask, color)
        # Mask Polygon
        # Pad to ensure proper polygons for masks that touch image edges.
        padded_mask = np.zeros(
            (mask.shape[0] + 2, mask.shape[1] + 2), dtype=np.uint8)
        padded_mask[1:-1, 1:-1] = mask
        contours = find_contours(padded_mask, 0.5)
        for verts in contours:
            # Subtract the padding and flip (y, x) to (x, y)
            verts = np.fliplr(verts) - 1
            p = Polygon(verts, facecolor="none", edgecolor=color)
            ax.add_patch(p)
    ax.imshow(masked_image.astype(np.uint8))
    plt.savefig("/home/Mask_RCNN/output/%s.jpg" % (str(count[1:26])),bbox_inches='tight',pad_inches=0.0)
    plt.show()

**Comment by shankdG** [comment]
[modified visualise.py for mrcnn to save images.txt](https://github.com/matterport/Mask_RCNN/files/3042113/modified.visualise.py.for.mrcnn.to.save.images.txt)
### modified visualise.py for mrcnn to save images.txt
###select the code in .txt file and copy the code inside visualise.py 
###change local directory in visualize.display_instances function 
###it works for n no of input images or frames

**Comment by sheep1234567** [comment]
Thanks! @lapetite123

**Comment by kunal-18** [comment]
I am getting assertion error somewhere near N=boxes.shape[0]

**Comment by ikraj** [comment]
> I am getting assertion error somewhere near N=boxes.shape[0]

@kunal-18 iam getting thre same error, do you resolve this issue?

**Comment by ronithsaju** [comment]
You just need to add the code `plt.savefig('your_desired_path_to_image.png')` inside **visualize.py**, between `ax.imshow(masked_image.astype(np.uint8))` (line 165) and `if auto_show:` (line 166). This will be inside the _display_instances_ function so whenever this function is called, the visualized image (with its mask, bounding box, label and confidence score) produced by the model will be saved.

My code is `plt.savefig('/gdrive/My Drive/DBM Model Results/‪DBM_%s.png' % (str(uuid.uuid4())), bbox_inches='tight')`, so the image is saved into a Google Drive folder, the image's name is randomised using uuid (remember to add `import uuid` as well) and the extra white blank space caused by the bounding box is reduced.

You can further edit the image by using the various parameters of savefig() as shown here: [https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html)

**Comment by Genius-farmer** [comment]
Dear all,

at visualise.py

```
line 571, in save_image
    masked_image = image.fromarray(masked_image)
AttributeError: 'numpy.ndarray' object has no attribute 'fromarray'
```

any advise how to fix this?
