### PR TITLE
TF 2.X & Keras 2.3.1 compatibility

### PR DESCRIPTION
**Pull request by IgnacioAmat**

### CODE REVIEW

**Comment by VictorAtPL** [comment]
@IgnacioAmat 
Are you able to train this model in Tensorflow 2.2.0 or still struggling with some incompatibilities?

**Comment by IgnacioAmat** [comment]
@VictorAtPL With the changes I proposed I was able to run the training without any incompatibilities, the model was well trained and showed good results

**Comment by VictorAtPL** [comment]
@IgnacioAmat 
Ok, is the training done in eager mode, or the graph is compilated?
If eventually I will be able to train on Tensorflow 2.2 I will have to extend the model with new _heads_. What I will need is a great debugging possibility and in Tensorflow 2.x it's easier than in Tensorflow 1.x, isn't it?

**Comment by IgnacioAmat** [comment]
@VictorAtPL 
As Tensorflow 2.X has eager mode by default I just trained the model with eager mode enabled.
Yes, Tensorflow 2.X offers way better debugging possibilities than Tensorflow 1.X, it allows debugging normal python code for example using pdb.

**Comment by VictorAtPL** [comment]
@IgnacioAmat
Okay, but did you use pdb to ensure that it's really in eager mode and you saw EagerTensors with values within them, or you just suppose it should be eager and nothing in Keras is graph by default?

**Comment by IgnacioAmat** [comment]
@VictorAtPL 
Oh sorry, there was a misunderstanding from my part ! No I actually executed the code based on graph definition, the Keras mode. I supposed it was eager mode as it was enabled by default, but didn't modify the code to actually execute it in eager mode.

**Comment by ivanlen** [comment]
I am having some issues with this PR.
Have you checked PR #2115?
Using both PRs together I am able to run everything on TF 2.x and keras 2.3.1.

**Comment by IgnacioAmat** [comment]
You were right @ivanlen, I forgot to add those changes too for the compatibility of TF 2.X. Thanks for the remark !

**Comment by RishikMani** [comment]
> You were right @ivanlen, I forgot to add those changes too for the compatibility of TF 2.X. Thanks for the remark !

Thank you very much. I was finally able to execute the code. Could you also let me know, were you able to start the training? As of now I have 350 training images and 50 validation images of size 256x256 with 4GB NVIDIA GTX 960. But it could not train and throws ran out of memory exception.

**Comment by IgnacioAmat** [comment]
Hi @RishikMani, you have to reduce your batch size to prevent running out of memory or reduce image size to lower resolution.

**Comment by ivanlen** [comment]
Hey @RishikMani Ideally you can use a generator, check out:

https://www.tensorflow.org/api_docs/python/tf/keras/utils/Sequence

**Comment by dsalnikov** [comment]
Hi, I get an error when trying to start training with this pr:

`ValueError: 
The following Variables were created within a Lambda layer (anchors)
but are not tracked by said layer:
  <tf.Variable 'anchors/Variable:0' shape=(1, 36720, 4) dtype=float32>
The layer cannot safely ensure proper Variable reuse across multiple
calls, and consquently this behavior is disallowed for safety. Lambda
layers are not well suited to stateful computation; instead, writing a
subclassed Layer is the recommend way to define layers with
Variables.`

How can I fix this?

**Comment by Shakesbeer333** [comment]
@dsalnikov there is a solution in the issue section

**Comment by kimile599** [comment]
> Hi @RishikMani, you have to reduce your batch size to prevent running out of memory or reduce image size to lower resolution.

Hi bro, i am using the mask r cnn and lowered the loss to 0.1 sometimes 0.09, but the bal_loss is not converging? any suggestions on that?

**Comment by Shakesbeer333** [comment]
Is this working with CUDA 10.2?

**Comment by IgnacioAmat** [comment]
Yes @Shakesbeer333

**Comment by IgnacioAmat** [comment]
Hi @kimile599, your problem may be that during training you are overfitting your data. Have you tried to increase you dataset size or using data augmentation ? Check these issues if to see if they can help you with your problem #281 and #527

**Comment by kimile599** [comment]
> Hi @kimile599, your problem may be that during training you are overfitting your data. Have you tried to increase you dataset size or using data augmentation ? Check these issues if to see if they can help you with your problem #281 and #527

Thank you for your reply. I am now doing the augmentation and try to flat the loss.

**Comment by jvdavim** [comment]
What about updating requirements.txt?

**Comment by IgnacioAmat** [comment]
@jvdavim Are you thinking about upgrading the minimal versions of both TF and keras to be something like: `
tensorflow>=2.0
keras>=2.3.1`?

**Comment by jvdavim** [comment]
Yes. But I just realized that there is no difference. It will install the latest version anyway.

**Comment by jvdavim** [comment]
I got this error.
`AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'`

tensorflow==2.3.1
keras==2.3.1

**Comment by IgnacioAmat** [comment]
Please check the comment of @NMazzatenta in this [issue](https://github.com/tensorflow/tensorflow/issues/38589)

**Comment by sirbastiano** [comment]
> @VictorAtPL With the changes I proposed I was able to run the training without any incompatibilities, the model was well trained and showed good results
Got this error running in Colab
ValueError: 
The following Variables were created within a Lambda layer (anchors)
but are not tracked by said layer:
  <tf.Variable 'anchors/Variable:0' shape=(8, 4092, 4) dtype=float32>
The layer cannot safely ensure proper Variable reuse across multiple
calls, and consquently this behavior is disallowed for safety. Lambda
layers are not well suited to stateful computation; instead, writing a
subclassed Layer is the recommend way to define layers with
Variables.

**Comment by sirbastiano** [comment]
Got this error:
ValueError: 
The following Variables were created within a Lambda layer (anchors)
but are not tracked by said layer:
  <tf.Variable 'anchors/Variable:0' shape=(8, 4092, 4) dtype=float32>
The layer cannot safely ensure proper Variable reuse across multiple
calls, and consquently this behavior is disallowed for safety. Lambda
layers are not well suited to stateful computation; instead, writing a
subclassed Layer is the recommend way to define layers with
Variables.

**Comment by IgnacioAmat** [comment]
@SirBastiano you seem to be having the same problem as @dsalnikov. You should maybe check this [issue](https://github.com/matterport/Mask_RCNN/issues/1930) to see if it helps, but as @Shakesbeer333 said, the solution to this is on the issue section

**Comment by sirbastiano** [comment]
Do you have a colab version of your work? I'm struggling for my master
thesis. ( This Is not my field of study)

Il lun 5 ott 2020, 14:42 Ignacio Amat <notifications@github.com> ha scritto:

**Comment by IgnacioAmat** [comment]
No, sorry @SirBastiano. Maybe @dsalnikov can give you a hint on how he managed to solve that problem.

**Comment by sirbastiano** [comment]
I figured out how to make it work. But now I receive this error:

TypeError                                 Traceback (most recent call last)

<ipython-input-19-a9b60817b002> <https://localhost:8080/#> in
<module>()      2 image_id = random.choice(dataset_val.image_ids)
3 original_image, image_meta, gt_class_id, gt_bbox, gt_mask =
modellib.load_image_gt(dataset_val, inference_config, ----> 4
                  image_id, use_mini_mask=True)      5       6
log("original_image", original_image)

TypeError: load_image_gt() got an unexpected keyword argument 'use_mini_mask'

It's when I test on a random image:

# Test on a random image
image_id = random.choice(dataset_val.image_ids)
original_image, image_meta, gt_class_id, gt_bbox, gt_mask =\
modellib.load_image_gt(dataset_val, inference_config,
image_id, use_mini_mask=True)

Il lun 5 ott 2020, 14:57 Ignacio Amat <notifications@github.com> ha scritto:

**Comment by IgnacioAmat** [comment]
You have to delete that parameter from model.py file as it is enabled by default in config.py as you can check in this [issue](https://github.com/matterport/Mask_RCNN/issues/2111)

**Comment by sirbastiano** [comment]
Thank you very much. I almost completed the debugging.

Il lun 5 ott 2020, 15:22 Ignacio Amat <notifications@github.com> ha scritto:

**Comment by sirbastiano** [comment]
Dear Ignacio, I've to ask you a question. I imported my own dataset and
masks but I get this error: 'Dataset' object non subscriptable. Do you know
what does this mean?

Il giorno lun 5 ott 2020 alle ore 19:42 Roberto Del Prete <
robertodelprete88@gmail.com> ha scritto:

**Comment by Ademord** [comment]
My basic test was to run the /samples notebooks. 
First one: demo, doesn't run.
The other ones have a lot of errors after mini masks section and data_generator.

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-aa019bc2cbcd> in <module>
     16 sys.path.append(ROOT_DIR)  # To find local version of the library
     17 from mrcnn import utils
---> 18 import mrcnn.model as modellib
     19 from mrcnn import visualize
     20 # Import COCO config

~/src/maskrcnn-amatt/mrcnn/model.py in <module>
     18 import numpy as np
     19 import tensorflow as tf
---> 20 import keras
     21 import keras.backend as K
     22 import keras.layers as KL

ModuleNotFoundError: No module named 'keras'
```

**Comment by IgnacioAmat** [comment]
> error: 'Dataset' object non subscriptable

Hi @SirBastiano, what I think you are trying to do while getting this error is to index an object that doesn't have that functionality. Check that your Dataset object can be subscriptable in order to avoid this problem. Can you provide some more code and error traceback ?

**Comment by sirbastiano** [comment]
Solved, thanks Ignacio.

Il mer 14 ott 2020, 10:07 Ignacio Amat <notifications@github.com> ha
scritto:

**Comment by IgnacioAmat** [comment]
> My basic test was to run the /samples notebooks.
> First one: demo, doesn't run.
> The other ones have a lot of errors after mini masks section and data_generator.
> 
> ```
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-aa019bc2cbcd> in <module>
>      16 sys.path.append(ROOT_DIR)  # To find local version of the library
>      17 from mrcnn import utils
> ---> 18 import mrcnn.model as modellib
>      19 from mrcnn import visualize
>      20 # Import COCO config
> 
> ~/src/maskrcnn-amatt/mrcnn/model.py in <module>
>      18 import numpy as np
>      19 import tensorflow as tf
> ---> 20 import keras
>      21 import keras.backend as K
>      22 import keras.layers as KL
> 
> ModuleNotFoundError: No module named 'keras'
> ```

Hi @Ademord, this error means that in your current environment you don't have the keras module installed. Install it with conda `conda install -c conda-forge keras` or with pip `pip install Keras`

**Comment by wiktor-jurek** [comment]
I think I may have found another incompatibility in the utils module. When calling utils.compute_ap(), that ends up performing an np.dot() calculation, but the two masks given have a shape mismatch. I've looked through the Utils code, but I can't find a reason as to why downgrading TF results in a successful operation. This is briefly mentioned in #960 , and the suggested advice is to downgrade TF.
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-1731946196d5> in <module>
     22     #precision_, recall_, AP_
     23     AP_, precision_, recall_, overlap_ = utils.compute_ap(gt_bbox, gt_class_id, gt_mask,
---> 24                                           r['rois'], r['class_ids'], r['scores'], r['masks'])
     25     #check if the vectors len are equal
     26     print("the actual len of the gt vect is : ", len(gt_tot))

~/project/2_MaskRCNN/mrcnn/utils.py in compute_ap(gt_boxes, gt_class_ids, gt_masks, pred_boxes, pred_class_ids, pred_scores, pred_masks, iou_threshold)
    716         gt_boxes, gt_class_ids, gt_masks,
    717         pred_boxes, pred_class_ids, pred_scores, pred_masks,
--> 718         iou_threshold)
    719 
    720     # Compute precision and recall at each prediction box step

~/project/2_MaskRCNN/mrcnn/utils.py in compute_matches(gt_boxes, gt_class_ids, gt_masks, pred_boxes, pred_class_ids, pred_scores, pred_masks, iou_threshold, score_threshold)
    669 
    670     # Compute IoU overlaps [pred_masks, gt_masks]
--> 671     overlaps = compute_overlaps_masks(pred_masks, gt_masks)
    672 
    673     # Loop through predictions and find matching ground truth boxes

~/project/2_MaskRCNN/mrcnn/utils.py in compute_overlaps_masks(masks1, masks2)
    118 
    119     # intersections and union
--> 120     intersections = np.dot(masks1.T, masks2)
    121     union = area1[:, None] + area2[None, :] - intersections
    122     overlaps = intersections / union

<__array_function__ internals> in dot(*args, **kwargs)

ValueError: shapes (2,65536) and (3136,43) not aligned: 65536 (dim 1) != 3136 (dim 0)
```

**Comment by Ademord** [comment]
If anyone was looking for an alternative to this repo I moved to Detectron2 and saw even better performance in terms of speed and accuracy, so I would recommend it.

**Comment by guilhermemarim** [comment]
Hi everyone! I'm using the TF 2.1.0 and keras 2.3.1 and I got this error: 

AttributeError: module 'tensorflow' has no attribute 'random_shuffle'

May someone help me?
