### ISSUE TITLE
Keras model is not appending layer losses

### ISSUE THREAD

**Issue by SimchaGD** [matterport/Mask_RCNN#2228]
My layer losses are not appending to metrics and I wonder why. This happens when compiling the model:
![image](https://user-images.githubusercontent.com/28702544/83667732-2709fa00-a5cf-11ea-9e8d-72814a1447a5.png)

left: output
right: ```mrcnn.model -> class MaskRCNN -> def compile```

Really weird because ```self.keras_model.metrics_names``` is a list and appending should work. 

This also causes that I am not seeing these losses in my tensorboard or at the progress bar.

EDIT: found out what the problem is, but not sure why it is in the source code. ```self.keras_model.metrics_names``` is not a list, but a property that outputs a list. But why would it work for other people?

**Comment by ShaunSpinelli** [comment]
Was having the same problem. Turned out to be a Keras version issue. It works with keras==2.0.8 .

**Comment by ysyyork** [comment]
when i'm testing on 2.0.8, i got this error
```
Traceback (most recent call last):
  File "train.py", line 386, in <module>
    main(cmd_args)
  File "train.py", line 338, in main
    self.keras_model.metrics.append(loss)
AttributeError: 'NoneType' object has no attribute 'append'
```
I copied this out into a custom training loop that's why my lines are different.

**Comment by ysyyork** [comment]
> My layer losses are not appending to metrics and I wonder why. This happens when compiling the model:
> ![image](https://user-images.githubusercontent.com/28702544/83667732-2709fa00-a5cf-11ea-9e8d-72814a1447a5.png)
> 
> left: output
> right: `mrcnn.model -> class MaskRCNN -> def compile`
> 
> Really weird because `self.keras_model.metrics_names` is a list and appending should work.
> 
> This also causes that I am not seeing these losses in my tensorboard or at the progress bar.
> 
> EDIT: found out what the problem is, but not sure why it is in the source code. `self.keras_model.metrics_names` is not a list, but a property that outputs a list. But why would it work for other people?

I don't think it works for other people, probably just a lot of people didn't know there are these separate metrics lol. they probably think the loss is the only metrics they can see.

And I figured out with keras 2.2.4. I think keras team probably changed the API. check this https://github.com/keras-team/keras/issues/9459#issuecomment-469282443  

So basically you need to do model.metrics_tensors instead of model.metrics. I tested and it works well.

**Comment by AndreyStille** [comment]
> > My layer losses are not appending to metrics and I wonder why. This happens when compiling the model:
> > ![image](https://user-images.githubusercontent.com/28702544/83667732-2709fa00-a5cf-11ea-9e8d-72814a1447a5.png)
> > left: output
> > right: `mrcnn.model -> class MaskRCNN -> def compile`
> > Really weird because `self.keras_model.metrics_names` is a list and appending should work.
> > This also causes that I am not seeing these losses in my tensorboard or at the progress bar.
> > EDIT: found out what the problem is, but not sure why it is in the source code. `self.keras_model.metrics_names` is not a list, but a property that outputs a list. But why would it work for other people?
> 
> I don't think it works for other people, probably just a lot of people didn't know there are these separate metrics lol. they probably think the loss is the only metrics they can see.
> 
> And I figured out with keras 2.2.4. I think keras team probably changed the API. check this [keras-team/keras#9459 (comment)](https://github.com/keras-team/keras/issues/9459#issuecomment-469282443)
> 
> So basically you need to do model.metrics_tensors instead of model.metrics. I tested and it works well.

Hi
If you have solved this issue please help. Same issue...  I've spent almost 3 days, but still no result.

**Comment by SimchaGD** [comment]
> 
> 
> > > My layer losses are not appending to metrics and I wonder why. This happens when compiling the model:
> > > ![image](https://user-images.githubusercontent.com/28702544/83667732-2709fa00-a5cf-11ea-9e8d-72814a1447a5.png)
> > > left: output
> > > right: `mrcnn.model -> class MaskRCNN -> def compile`
> > > Really weird because `self.keras_model.metrics_names` is a list and appending should work.
> > > This also causes that I am not seeing these losses in my tensorboard or at the progress bar.
> > > EDIT: found out what the problem is, but not sure why it is in the source code. `self.keras_model.metrics_names` is not a list, but a property that outputs a list. But why would it work for other people?
> > 
> > 
> > I don't think it works for other people, probably just a lot of people didn't know there are these separate metrics lol. they probably think the loss is the only metrics they can see.
> > And I figured out with keras 2.2.4. I think keras team probably changed the API. check this [keras-team/keras#9459 (comment)](https://github.com/keras-team/keras/issues/9459#issuecomment-469282443)
> > So basically you need to do model.metrics_tensors instead of model.metrics. I tested and it works well.
> 
> Hi
> If you have solved this issue please help. Same issue... I've spent almost 3 days, but still no result.

It's been a while, but I solved it by degrading Keras. I'm not sure if this works for you though, since this issue is quite old.
