### ISSUE TITLE
module 'utils' has no attribute 'Dataset'

### ISSUE THREAD

**Issue by saisriteja** [matterport/Mask_RCNN#1332]
I am getting this error while inspecting model...i had trained on own dataset.
module 'utils' has no attribute 'Dataset'
I am working in CPU windows8.1.........

**Comment by mehdiselbi** [comment]
i got the same error using the MRCNN 2.1

**Comment by saisriteja** [comment]
@selbimehdi
Check the configuration file once again you will achieve it....
let me know if you have any more errors

https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_resnet101_pets.config

**Comment by mehdiselbi** [comment]
@saisriteja 
the link is broken

**Comment by saisriteja** [comment]
@selbimehdi I updated it check it.
